# This workflow will build a Release image of the Exercises Application. It will build and push the image to Docker Hub.
# This workflow requires a release branch.

name: Exercises Release

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Confirm Release publish the image to Dockerhub'
        default: 'Confirm'
        required: true
#  push:
#    branches: [ "main" ]
#  pull_request:
#    branches: [ "main" ]" ]
env:
  BRANCH_NAME: $GITHUB_REF_NAME
jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
    - name: Echo variables
      run: echo "vars.RELEASE_VERSION ${{vars.RELEASE_VERSION}}, github.ref_name ${{github.ref_name}}"
  build:
    if: contains(github.ref_name, vars.RELEASE_VERSION) 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    -
      name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    -
      name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ./DockerfileAws
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/course:exercises-${{vars.RELEASE_VERSION}}
        
      
